language: java
os:
- linux
jdk:
- openjdk11
dist: xenial

addons:
  sonarcloud:
    organization: "riccardoburaioli"
    token:
      secure:f82b2ad6ab1332e4a256035c04392a10fe83ee0e


script:
 - ant build
 - sonar-scanner

 